wandb_version: 1

activation:
  value: gelu
batch_size:
  value: 203
cutout:
  value: 'true'
cutout_length:
  value: 15
data_root:
  value: ./data
epochs:
  value: 127
lr:
  value: 0.03765891216984535
momentum:
  value: 0.9165069815081144
nesterov:
  value: 'true'
optimizer:
  value: rmsprop
out_dir:
  value: results/act_tanh
scheduler:
  value: none
seed:
  value: 34
wandb_project:
  value: cs6886w-vgg6
weight_decay:
  value: 0.0002705406948984446
